name: Publish docker image 

on: push

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build . --tag ghcr.io/yannickschlaepferb/ref_card_02:latest
          docker push ghcr.io/yannickschlaepferb/ref_card_02:latest

      - name: Login to AWS ECR
        run: |
          echo "${{ secrets.AWS_PASSWORD }}" | docker login --username AWS --password-stdin 677318853776.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com  

      - name: Build/Tag
        run: |
          docker tag ghcr.io/yannickschlaepferb/ref_card_02:latest 677318853776.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/refcard02:latest
          docker push 677318853776.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/refcard02:latest