name: Publish Docker image to Github Container Registry

on: push

jobs:
  push_to_registry:
    name: Push Docker image to Github Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build . --tag ghcr.io/yannickschlaepferb/ref_card_02:latest
          docker push ghcr.io/yannickschlaepferb/ref_card_02:latest
